/*
 *  The TOAD JavaScript/TypeScript GUI Library
 *  Copyright (C) 2018-2021 Mark-André Hopf <mhopf@mark13.org>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Model Messages (generated by model)
export const INSERT_ROW = Symbol("INSERT_ROW")
export const REMOVE_ROW = Symbol("REMOVE_ROW")
export const INSERT_COL = Symbol("INSERT_COL")
export const REMOVE_COL = Symbol("REMOVE_COL")
export const CELL_CHANGED = Symbol("CELL_CHANGED")

// TableAdapter messages (not generated by models)
export const RESIZE_ROW = Symbol("RESIZE_ROW")
export const RESIZE_COL = Symbol("RESIZE_COL")
export const CHANGED = Symbol("CHANGED")

export type TableEventType = typeof INSERT_ROW | typeof REMOVE_ROW | typeof INSERT_COL | typeof REMOVE_COL | typeof CELL_CHANGED | typeof RESIZE_ROW | typeof CHANGED